### ISSUE TITLE
web version showing error

### ISSUE THREAD

**Issue by sandraleung** [joholl/tpmstream#22]
https://joholl.github.io/tpmstream-web/ shows the following:

(PY1001): Unable to install package(s) 'tpmstream'. Reason: Traceback (most recent call last): File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install await transaction.gather_requirements(requirements) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements await gather(*requirement_promises) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 349, in add_requirement return await self.add_requirement_inner(Requirement(req)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/micropip/_micropip.py", line 457, in add_requirement_inner await self.add_wheel(wheel, req.extras) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 470, in add_wheel await wheel.download(self.fetch_kwargs) File "/lib/python3.11/site-packages/micropip/_micropip.py", line 176, in download data = await self._fetch_bytes(fetch_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/micropip/_micropip.py", line 166, in _fetch_bytes raise e File "/lib/python3.11/site-packages/micropip/_micropip.py", line 160, in _fetch_bytes return await fetch_bytes(self.url, fetch_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/micropip/_compat_in_pyodide.py", line 29, in fetch_bytes result_bytes = await (await pyfetch(url, **kwargs)).bytes() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python311.zip/pyodide/http.py", line 254, in pyfetch raise OSError(e.message) from None OSError: Failed to fetch . Please open an issue at https://github.com/pyscript/pyscript/issues/new if you require help or you think it's a bug.

**Comment by joholl** [comment]
@sandraleung I cannot reproduce it. Do you have any ad bockers/script blocker installed?

It works for me both on desktop and mobile.
